name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v4
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run tests
      run: go test -v
    - name: Build and tag Docker image
      run: docker image build -t awenzelhuemer/myhello:${{ github.sha }} ./
    - name: Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN  }}
    - name: Push image to Docker
      run: |
        docker image push awenzelhuemer/myhello:${{ github.sha }}
        docker image push awenzelhuemer/myhello:latest
